version: "3.6"

services:

  base:
    image: securesystemslab/lind:base
    build:
      context: base
      dockerfile: Dockerfile
    volumes:
      - ./lind_project:/usr/lind_project

  prebuiltsdk:
    image: securesystemslab/lind:prebuiltsdk
    build:
      context: prebuiltsdk
      dockerfile: Dockerfile
    volumes:
      - ./lind_project:/usr/lind_project

  latest:
    image: securesystemslab/lind:latest
    volumes:
      - ./lind_project:/usr/lind_project
    build:
      context: prebuiltsdk
      dockerfile: Dockerfile
      cache_from:
        - securesystemslab/lind:prebuiltsdk
